captcha:
  restart: always
  image: captcha
  ports:
    - 8008:80
  volumes:
    - /opt/data:/opt/data

dev:
  image: captcha
  ports:
    - 8008:80
  volumes:
    - ./data:/opt/data
    - ./captcha:/var/www/captcha

